### ISSUE TITLE
Desktop Build Question

### ISSUE THREAD

**Issue by bobflorian** [NickCraver/nickcraver.github.com#51]
Hey!  Love the desktop build posts, still using a 2016 build from your site right now :-). Time to upgrade though, will you be updating these anymore given it seems you primarily did these for Stack Overflow?  Or did anyone at Stack Overflow take over the reigns for their dev computer builds?

**Comment by NickCraver** [comment]
Hey Bob! I'm not sure what to do about these - Stack Overflow went to more standard builds for IT scalability in the most recent years, and I'm not aware of anyone keeping up with the custom. More generally though: it's hard to get parts still with the shortages so the scenario of recommending a parts combination you can readily get isn't the case right now. I'm still custom building, for example here's my current: https://pcpartpicker.com/user/NickCraver/saved/htgBLk ...I just didn't want to recommend that to people because it's not as budget friendly (esp with shortages/markup) and harder to get parts. Curious on thoughts here!

**Comment by bobflorian** [comment]
Hey Nick, I ended up finding everything I needed and more at MicroCenter actually!  They actually had everything in stock too, which really surprised me!

<html>
<body>


SKU | Description | Quantity | Price Per | Total Price
-- | -- | -- | -- | --
326694 | INTEL INTEL I9-12900K BOXS/N: U21W3B8501742 | 1 | 549.99 | 549.99
335802 | MSI MPG Z690 EDGE WIFI D4S/N: 601-7D31-010B2201007429 | 1 | 279.99 | 279.99
  | Price Protection |   |   |  
046177 | CORSAIR 32GB 2X16 RGB D4 3200 C16 | 1 | 129.99 | 129.99
225219 | CORSAIR RM850X FM 80+G ATX 2021 | 1 | 159.99 | 159.99
283739 | EVGA RTX3080TI FTW3 ULT GAMINGS/N: 2210103967004357 | 1 | 1299.99 | 1299.99
229948 | SAMSUNG E 2TB 980PRO NVME GEN4SSDS/N: S6B0NS0T406601 | 1 | 279.99 | 279.99
  | Price Protection |   |   |  
337949 | BEQUIET DARK ROCK PRO 4 COOLER | 1 | 109.99 | 109.99
229534 | THERMAL G THERML GRIZLY KRYONAUT 1G | 1 | 11.99 | 11.99
880385 | CORSAIR CRYSTAL 680X RGB TGATX WT | 1 | 264.99 | 264.99
418806 | IPSG INLAND USB-A3 4S CARDR | 1 | 10.99 | 10.99


</body>
</html>

**Comment by NickCraver** [comment]
Nice - good luck with your build!!
